fix: version conf
roclub/helm-charts pull request #42
Opened 2024-04-13 09:20 UTC by dlange82

2024-04-14 11:52 UTC, holgerson97 requested changes

2024-04-14 11:52 UTC, holgerson97 commented on charts/roclub-conference/Chart.yaml
Das ist die selbe Version

2024-04-14 16:32 UTC, dlange82 commented on charts/roclub-conference/Chart.yaml
frontend 0.4.0, chart: 0.4.1, was meinst Du? Beides neu

2024-04-14 16:35 UTC, dlange82 commented on charts/roclub-conference/Chart.yaml
Hast recht. Fixed

2024-04-15 07:02 UTC, holgerson97 approved these changes
GEILO

2024-04-15 07:02 UTC, merged